-- Generated from the Blender geometry handoff by sync_scenario_outputs.py.
-- Do not edit runtime light transforms independently.
return {
  {
    name = "ericrolph_cannon_car_wash_lowvram_light_anchor_tunnel_01",
    role = "tunnel_fluorescent_fill",
    class = "PointLight",
    local_position = {0.0, -6.8, 4.34},
    color = {0.56, 0.82, 1.0},
    intensity = 11000.0,
    intensity_unit = "lm",
    radius = 9.0,
    cast_shadows = false,
  },
  {
    name = "ericrolph_cannon_car_wash_lowvram_light_anchor_tunnel_03",
    role = "tunnel_fluorescent_fill",
    class = "PointLight",
    local_position = {0.0, 0.0, 4.34},
    color = {0.56, 0.82, 1.0},
    intensity = 11000.0,
    intensity_unit = "lm",
    radius = 9.0,
    cast_shadows = false,
  },
  {
    name = "ericrolph_cannon_car_wash_lowvram_light_anchor_tunnel_05",
    role = "tunnel_fluorescent_fill",
    class = "PointLight",
    local_position = {0.0, 6.8, 4.34},
    color = {0.56, 0.82, 1.0},
    intensity = 11000.0,
    intensity_unit = "lm",
    radius = 9.0,
    cast_shadows = false,
  },
  {
    name = "ericrolph_cannon_car_wash_lowvram_light_anchor_exit_left",
    role = "exit_spill",
    class = "SpotLight",
    local_position = {-1.9, 8.72, 4.08},
    local_direction = {0.0, 0.97, -0.24},
    color = {0.1, 0.64, 1.0},
    intensity = 2500.0,
    intensity_unit = "cd",
    range = 10.0,
    inner_angle_degrees = 28.0,
    outer_angle_degrees = 48.0,
    cast_shadows = false,
  },
  {
    name = "ericrolph_cannon_car_wash_lowvram_light_anchor_exit_right",
    role = "exit_spill",
    class = "SpotLight",
    local_position = {1.9, 8.72, 4.08},
    local_direction = {0.0, 0.97, -0.24},
    color = {0.1, 0.64, 1.0},
    intensity = 2500.0,
    intensity_unit = "cd",
    range = 10.0,
    inner_angle_degrees = 28.0,
    outer_angle_degrees = 48.0,
    cast_shadows = false,
  },
}
